import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import * as fsMod from 'fs';
import * as osMod from 'os';
import path from 'path';
import {
  CHAIN_VERSION, MERKLE_VERSION, ZERO_HASH, ChainState, ChainedJournal, buildTree, chainLine, hashCombine, hashLeaf,
  lineHash, merkleRoot, proofFor, sessionRoot, splitChainedLine, trailingHash, verifyLines, verifyProof, versionFields,
} from './provenance';

/**
 * The known-answer files are the claim; this code is checked against
 * them. `merkle-kat.jsonl` is arborist's own vector file (one hash
 * grammar across arborist, Go, Python and here); `chain-kat.jsonl` is
 * generated by uncloseai-cli's Python writer and replayed here, so a
 * line the harness writes and a verdict this ingester reaches are
 * pinned to each other by a test in BOTH repos, not by either reading
 * the other's code.
 */
const FIXTURES = path.resolve(__dirname, '../schema/fixtures');

function records(name: string, kind?: string): any[] {
  return readFileSync(path.join(FIXTURES, name), 'utf8')
    .split('\n')
    .filter((l) => l.trim() && !l.startsWith('#'))
    .map((l) => JSON.parse(l))
    .filter((r) => !kind || r.kind === kind);
}

const hex = (b: Buffer) => b.toString('hex');

describe('merkle-v1 known answers (arborist vectors)', () => {
  it('pins the version the fixture was generated for', () => {
    const versions = new Set(records('merkle-kat.jsonl').map((r) => r.version));
    expect([...versions]).toEqual([MERKLE_VERSION]);
  });

  it('leaf vectors', () => {
    for (const r of records('merkle-kat.jsonl', 'leaf')) {
      expect(hex(hashLeaf(Buffer.from(r.content_hex, 'hex'))), r.label).toBe(r.leaf_hash_hex);
    }
  });

  it('combine vectors are non-commutative', () => {
    for (const r of records('merkle-kat.jsonl', 'combine')) {
      const left = Buffer.from(r.left_hex, 'hex');
      const right = Buffer.from(r.right_hex, 'hex');
      expect(hex(hashCombine(left, right)), r.label).toBe(r.combined_hex);
      if (!left.equals(right)) expect(hex(hashCombine(right, left))).not.toBe(r.combined_hex);
    }
    expect(() => hashCombine(Buffer.from('short'), ZERO_HASH)).toThrow();
  });

  it('tree vectors, including layer widths (the odd-element rule)', () => {
    for (const r of records('merkle-kat.jsonl', 'tree')) {
      const layers = buildTree(r.leaf_hashes_hex.map((h: string) => Buffer.from(h, 'hex')));
      expect(hex(merkleRoot(layers[0])), r.label).toBe(r.root_hex);
      expect(layers.map((l) => l.length), r.label).toEqual(r.layer_widths);
    }
  });

  it('proof vectors verify, and a flipped sibling side fails', () => {
    const proofs = records('merkle-kat.jsonl', 'proof');
    for (const r of proofs) {
      const proof = { leaf: r.leaf_hex, leaf_index: r.leaf_index, siblings: r.siblings, root: r.root_hex };
      expect(verifyProof(proof), r.label).toBe(r.expect_valid);
    }
    const r = proofs.find((p) => p.expect_valid && p.siblings.length)!;
    const tampered = {
      leaf: r.leaf_hex, leaf_index: r.leaf_index, root: r.root_hex,
      siblings: r.siblings.map((s: any, i: number) => (i === 0 ? { ...s, is_left: !s.is_left } : s)),
    };
    expect(verifyProof(tampered)).toBe(false);
  });

  it('proofs generated here match the fixture path for every leaf', () => {
    for (const t of records('merkle-kat.jsonl', 'tree').filter((t) => t.leaf_count > 0)) {
      const layers = buildTree(t.leaf_hashes_hex.map((h: string) => Buffer.from(h, 'hex')));
      for (let i = 0; i < t.leaf_count; i++) {
        const p = proofFor(layers, i);
        const want = records('merkle-kat.jsonl', 'proof')
          .find((r) => r.leaf_count === t.leaf_count && r.leaf_index === i);
        if (want) expect(p.siblings, `${t.label}/${i}`).toEqual(want.siblings);
        expect(verifyProof(p)).toBe(true);
      }
    }
    expect(() => proofFor(buildTree([]), 0)).toThrow();
    expect(() => proofFor(buildTree([hashLeaf(Buffer.from('x'))]), 1)).toThrow();
  });
});

describe('unfirehose-chain-v1 known answers (the Python writer’s vectors)', () => {
  it('line vectors: preimage bytes hash to the writer’s hash, and the tail splits off', () => {
    for (const r of records('chain-kat.jsonl', 'line')) {
      expect(r.version).toBe(CHAIN_VERSION);
      const pre = Buffer.from(r.preimage, 'utf8');
      expect(lineHash(pre), r.label).toBe(r.hash);
      const split = splitChainedLine(r.line)!;
      expect(split.hash, r.label).toBe(r.hash);
      expect(split.preimage.equals(pre), r.label).toBe(true);
      const entry = JSON.parse(r.preimage);
      expect(entry.prevHash).toBe(r.prev);
      expect('hash' in entry).toBe(false);
    }
  });

  it('session vectors reach the writer’s verdict, break index and root', () => {
    for (const r of records('chain-kat.jsonl', 'session')) {
      const rep = verifyLines(r.lines);
      for (const [key, want] of Object.entries(r.expect)) {
        expect((rep as any)[key], `${r.label}.${key}`).toEqual(want);
      }
    }
  });

  it('every verdict is exercised by the fixture', () => {
    const states = new Set(records('chain-kat.jsonl', 'session').map((r) => r.expect.state));
    expect([...states].sort()).toEqual(['corrupted', 'open', 'unchained', 'verified']);
  });

  it('proof vectors: a line hash proves membership in its session root', () => {
    for (const r of records('chain-kat.jsonl', 'proof')) {
      expect(r.proof.leaf, r.label).toBe(hex(hashLeaf(Buffer.from(r.line_hash, 'hex'))));
      expect(verifyProof(r.proof), r.label).toBe(r.expect_valid);
    }
  });

  it('sessionRoot over the n=5 vector’s leaves equals the fixture root', () => {
    const r = records('chain-kat.jsonl', 'session').find((s) => s.label === 'verified/n=5');
    const hashes = r.lines.map((l: string) => splitChainedLine(l)!.hash);
    expect(sessionRoot(hashes.slice(0, r.expect.root_expected ? hashes.length - 2 : 0)))
      .toBe(r.expect.root_expected);
  });
});

describe('the rules a root was minted under', () => {
  it('are recorded from the closed record and match this reader', () => {
    const r = records('chain-kat.jsonl', 'session').find((s) => s.label === 'verified/n=3');
    const rep = verifyLines(r.lines);
    expect([rep.merkle_version, rep.encoding_version, rep.root_semantics, rep.hash_version])
      .toEqual(['merkle-v1', 'jsonl-bytes-v1', 'SEQUENCE', 'unfirehose-chain-v1']);
    expect(rep.state).toBe('verified');
  });

  it('a root minted under rules this reader does not implement is a break, not a silent match', () => {
    const r = records('chain-kat.jsonl', 'session').find((s) => s.label === 'verified/n=2');
    const lines: string[] = r.lines.slice(0, -2);
    const prev = splitChainedLine(lines[lines.length - 1])!.hash;
    // Re-chain a closed record that names a different merkle grammar.
    const body = JSON.stringify({ type: 'session', id: 'kat', status: 'closed',
      sessionRoot: r.expect.root_expected, hashVersion: 'unfirehose-chain-v1',
      merkleVersion: 'merkle-v2', rootSemantics: 'SET', prevHash: prev });
    const line = body.slice(0, -1) + ',"hash":"' + lineHash(Buffer.from(body, 'utf8')) + '"}';
    const rep = verifyLines([...lines, line]);
    expect(rep.first_break_reason).toBe('unknown_rules');
    expect(rep.state).toBe('corrupted');
  });

  it('a record from before the rules were named verifies under the defaults', () => {
    const r = records('chain-kat.jsonl', 'session').find((s) => s.label === 'verified/n=2');
    const lines: string[] = r.lines.slice(0, -2);
    const prev = splitChainedLine(lines[lines.length - 1])!.hash;
    const body = JSON.stringify({ type: 'session', id: 'kat', status: 'closed',
      sessionRoot: r.expect.root_expected, hashVersion: 'unfirehose-chain-v1', prevHash: prev });
    const line = body.slice(0, -1) + ',"hash":"' + lineHash(Buffer.from(body, 'utf8')) + '"}';
    const rep = verifyLines([...lines, line]);
    expect(rep.state).toBe('verified');
    expect(rep.merkle_version).toBeNull();
  });
});

describe('splitChainedLine shape gate', () => {
  const good = records('chain-kat.jsonl', 'line')[0].line as string;
  it('rejects every wrong shape and tolerates a trailing newline', () => {
    for (const bad of ['', '{}', good.slice(0, -1), good.slice(0, -76) + '}',
      good.replace('"hash":"', '"hash":"Z'), good.slice(0, -75) + ',"hash":"' + '0'.repeat(63) + '"}']) {
      expect(splitChainedLine(bad), bad.slice(-20)).toBeNull();
    }
    expect(splitChainedLine(good + '\r\n')).not.toBeNull();
  });
});

describe('ChainState incremental use', () => {
  it('resumes from persisted data and leaves exactly as a single pass would', () => {
    const r = records('chain-kat.jsonl', 'session').find((s) => s.label === 'verified/n=8');
    const one = new ChainState();
    for (const l of r.lines) one.feed(l);
    const first = new ChainState();
    for (const l of r.lines.slice(0, 4)) first.feed(l);
    const persisted = JSON.parse(JSON.stringify({ data: first.data, leaves: first.leaves }));
    const second = new ChainState(persisted.data, persisted.leaves);
    for (const l of r.lines.slice(4)) second.feed(l);
    expect(second.data).toEqual(one.data);
    expect(second.verdict).toBe('verified');
  });

  it('a chained line with a valid hash but unparseable body is a break', () => {
    const pre = 'not json}';
    const line = pre.slice(0, -1) + ',"hash":"' + lineHash(Buffer.from(pre)) + '"}';
    const rep = verifyLines([line]);
    expect(rep.first_break_reason).toBe('unparseable');
    expect(rep.state).toBe('corrupted');
  });
});

describe('the writer side', () => {
  it('chainLine produces a line the verifier accepts and owns its two keys', () => {
    const a = chainLine({ type: 'session', id: 's', hash: 'smuggled', prevHash: 'smuggled' }, null);
    const b = chainLine({ type: 'message', role: 'user', content: 'é 日本 🦊' }, a.hash);
    const rep = verifyLines([a.line, b.line]);
    expect(rep.state).toBe('open');
    expect(rep.breaks).toBe(0);
    const entry = JSON.parse(splitChainedLine(a.line)!.preimage.toString('utf8'));
    expect(entry).toEqual({ type: 'session', id: 's', prevHash: null });
  });

  it('a ChainedJournal continues its chain across re-opens and closes with a root that verifies', () => {
    const { mkdtempSync, readFileSync, rmSync } = fsMod;
    const { tmpdir } = osMod;
    const dir = mkdtempSync(path.join(tmpdir(), 'cj-'));
    const file = path.join(dir, 's.jsonl');
    try {
      const j1 = new ChainedJournal(file);
      j1.append({ type: 'session', id: 's', status: 'active', ...versionFields() });
      j1.append({ type: 'message', role: 'user', content: [{ type: 'text', text: 'one' }] });
      const j2 = new ChainedJournal(file);                // re-opened: recovers the head
      j2.append({ type: 'message', role: 'assistant', content: [{ type: 'text', text: 'two' }] });
      j2.close({ id: 's' });
      const rep = verifyLines(readFileSync(file, 'utf8').split('\n'));
      expect(rep.state).toBe('verified');
      expect(rep.entries).toBe(4);
      expect([rep.merkle_version, rep.root_semantics]).toEqual(['merkle-v1', 'SEQUENCE']);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('trailingHash', () => {
  it('reads the claimed hash off a chained line without building its preimage', () => {
    const { line, hash } = chainLine({ type: 'telemetry', n: 1 }, null);
    expect(trailingHash(line)).toBe(hash);
    expect(trailingHash(line + '\r\n')).toBe(hash);
    expect(trailingHash(line)).toBe(splitChainedLine(line)!.hash);
    expect(trailingHash('{"type":"telemetry"}')).toBeNull();
    expect(trailingHash(line.slice(0, -3) + 'Z"}')).toBeNull();     // not hex
    expect(trailingHash('')).toBeNull();
  });
});
